name: otp
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.10
  razorpay_flutter: ^1.2.2
  fluttertoast: ^7.1.1
  flutter_markdown: ^0.4.1
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1
  firebase_auth: ^0.18.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1

flutter_launcher_name:
  name: "POG"

flutter:
  assets:
    - image/
    - assets/

  fonts:
    - family: Marmelad
      fonts:
        - asset: assets/marmelad.ttf

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "image/logo.png"
